name: Docker Image CI

on: push
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
       username: ${{ secrets.USERNAME }}
       password: ${{ secrets.PASSWORD }}
       repository: html-server
       tags: latest
